pipeline {
     agent any
     stages {
         stage('Install Sonarqube') {
	     steps {
		 script {
	          sh '''
		   echo "Installing the Sonarqube..."
                   sonarqube_setup/install_sonarqube.sh
		   sonarqube_setup/sonarqube.properties
                   sonarqube_setup/sonarqube.service
		   '''
		  }
	     }
	 }

     }
      
}
